//! Installation plan assembly and execution for the Kleos installer.
//!
//! `InstallPlan` is assembled by the TUI wizard or non-interactive runner and
//! drives the complete installation sequence: release fetch, download, verify,
//! install, config write, and system integration.

use std::path::{Path, PathBuf};

use crate::components::Platform;
use crate::config::InstallerConfig;
use crate::download::{
    download_component, fetch_checksums, fetch_latest_release, fetch_release, DownloadProgress,
};
use crate::error::InstallError;
use crate::system::{
    generate_launchd_plist, generate_systemd_unit, install_launchd_plist, install_systemd_unit,
    SystemIntegration,
};

/// GitHub repository used when fetching release assets.
const GITHUB_REPO: &str = "Ghost-Frame/Kleos";

/// Complete installation plan assembled from all wizard choices.
///
/// Passed to `InstallPlan::execute` to perform the actual installation.
#[derive(Debug, Clone)]
pub struct InstallPlan {
    /// Component IDs that will be downloaded and installed.
    pub components: Vec<String>,
    /// Directory where binaries will be placed.
    pub install_dir: PathBuf,
    /// Directory where configuration files will be written.
    pub config_dir: PathBuf,
    /// Release tag to install (e.g. "v1.2.1"), or "latest".
    pub version: String,
    /// Full installer configuration generated by the wizard.
    pub config: InstallerConfig,
    /// System service integration choice.
    pub system_integration: SystemIntegration,
    /// `true` when upgrading an existing installation, `false` for a fresh install.
    pub is_upgrade: bool,
}

/// Callback interface for reporting installation progress to the UI layer.
///
/// Implemented separately by the TUI and GUI frontends so that all download
/// and install logic is completely decoupled from presentation.
pub trait InstallProgress: Send + Sync {
    /// Called at the start of a major installation phase.
    fn on_phase(&self, phase: &str, detail: &str);
    /// Called periodically during a component download.
    fn on_download_progress(&self, component: &str, bytes: u64, total: u64);
    /// Called once after a component binary is successfully installed.
    fn on_component_installed(&self, component: &str);
    /// Called once when the entire installation completes successfully.
    fn on_complete(&self);
    /// Called when a fatal error stops the installation.
    fn on_error(&self, error: &InstallError);
}

/// Summary of a successfully completed installation.
#[derive(Debug, Clone)]
pub struct InstallResult {
    /// Component IDs that were installed.
    pub installed_components: Vec<String>,
    /// Directory where the binaries were placed.
    pub install_dir: PathBuf,
    /// Path to the written `engram.toml` file.
    pub config_path: PathBuf,
    /// The initial API key generated for the first user.
    pub api_key: String,
    /// The server URL if a server component was installed, formatted as `http://host:port`.
    pub server_url: Option<String>,
}

/// Internal adapter that bridges `InstallProgress` to the `DownloadProgress` trait
/// required by the download layer.
struct DownloadProgressAdapter<'a> {
    /// The upstream progress receiver.
    inner: &'a dyn InstallProgress,
}

impl<'a> DownloadProgress for DownloadProgressAdapter<'a> {
    /// Forward per-chunk progress to the install progress handler.
    fn on_progress(&self, component: &str, bytes_downloaded: u64, total_bytes: u64) {
        self.inner
            .on_download_progress(component, bytes_downloaded, total_bytes);
    }

    /// Verification is implicit in the download flow -- ignored here.
    fn on_verifying(&self, _component: &str) {}

    /// Forward completion to the install progress handler.
    fn on_complete(&self, component: &str) {
        self.inner.on_component_installed(component);
    }

    /// Errors are propagated via `Result` -- ignored here.
    fn on_error(&self, _component: &str, _error: &str) {}
}

impl InstallPlan {
    /// Execute the installation plan, reporting progress via `progress`.
    ///
    /// Steps in order:
    /// 1. Fetch GitHub release metadata.
    /// 2. Download the SHA256SUMS asset.
    /// 3. Download each selected component binary.
    /// 4. Verify checksums for all downloaded files.
    /// 5. Move binaries to `install_dir` and set executable permissions on Unix.
    /// 6. Write `engram.toml` and `.env` to `config_dir`.
    /// 7. Install system integration (systemd unit, launchd plist, or nothing).
    /// 8. Return an `InstallResult` summarising the completed installation.
    ///
    /// The `repo` parameter overrides `GITHUB_REPO` when non-empty. Pass an
    /// empty string to use the built-in default.
    pub fn execute(
        &self,
        progress: &dyn InstallProgress,
        repo: &str,
    ) -> Result<InstallResult, InstallError> {
        let repo = if repo.is_empty() { GITHUB_REPO } else { repo };
        let adapter = DownloadProgressAdapter { inner: progress };

        // Step 1: fetch release metadata.
        progress.on_phase("fetch", "Fetching release metadata from GitHub");
        let release = if self.version == "latest" {
            fetch_latest_release(repo)?
        } else {
            fetch_release(repo, &self.version)?
        };

        // Step 2: download checksums.
        progress.on_phase("checksums", "Downloading SHA256SUMS");
        let checksums = fetch_checksums(&release)?;

        // Step 3 + 4: download and verify each component.
        let platform = Platform::detect();
        let suffix = platform.release_suffix();
        let tmp_dir = make_tempdir()?;
        let mut pending: Vec<(String, String, PathBuf)> = Vec::new();

        for component_id in &self.components {
            let asset_name = format!("{component_id}-{suffix}");
            let asset_name_exe = format!("{asset_name}.exe");

            progress.on_phase("download", &format!("Downloading {asset_name}"));

            let asset = release
                .assets
                .iter()
                .find(|a| a.name == asset_name || a.name == asset_name_exe)
                .ok_or_else(|| {
                    InstallError::Download(format!(
                        "asset '{asset_name}' not found in release {}",
                        release.tag_name
                    ))
                })?;

            let dest = tmp_dir.join(&asset.name);
            let expected_hash = checksums.get(&asset.name).map(|s| s.as_str());

            download_component(asset, &dest, expected_hash, &adapter)?;
            pending.push((component_id.clone(), asset.name.clone(), dest));
        }

        // Step 5: install binaries.
        progress.on_phase("install", "Installing binaries");
        std::fs::create_dir_all(&self.install_dir)?;

        for (component_id, _asset_name, tmp_path) in &pending {
            let bin_name = if cfg!(windows) {
                format!("{component_id}.exe")
            } else {
                component_id.clone()
            };
            let dest = self.install_dir.join(&bin_name);
            std::fs::copy(tmp_path, &dest)?;

            #[cfg(unix)]
            set_executable(&dest)?;

            progress.on_component_installed(component_id);
        }

        // Step 6: write configuration.
        progress.on_phase("config", "Writing configuration files");
        self.config.write_config(&self.config_dir)?;

        // Step 7: system integration.
        progress.on_phase("service", "Setting up system integration");
        setup_system_integration(
            &self.system_integration,
            &self.config,
            &self.install_dir,
            &self.config_dir,
        )?;

        // Step 8: build result.
        let server_url = self
            .config
            .server
            .as_ref()
            .map(|s| format!("http://{}:{}", s.host, s.port));

        let result = InstallResult {
            installed_components: self.components.clone(),
            install_dir: self.install_dir.clone(),
            config_path: self.config_dir.join("engram.toml"),
            api_key: self.config.security.initial_api_key.clone(),
            server_url,
        };

        progress.on_complete();
        Ok(result)
    }
}

/// Install the chosen system service integration.
fn setup_system_integration(
    integration: &SystemIntegration,
    config: &InstallerConfig,
    install_dir: &Path,
    config_dir: &Path,
) -> Result<(), InstallError> {
    match integration {
        SystemIntegration::Systemd { auto_start } => {
            let unit = generate_systemd_unit(config, install_dir, config_dir);
            install_systemd_unit(&unit, *auto_start)?;
        }
        SystemIntegration::Launchd { auto_start } => {
            let plist = generate_launchd_plist(config, install_dir, config_dir);
            install_launchd_plist(&plist, *auto_start)?;
        }
        SystemIntegration::WindowsService => {
            // Windows Service installation requires elevated privileges and
            // `sc.exe` -- left as a no-op in the library. The GUI layer is
            // responsible for invoking the platform-specific installer.
        }
        SystemIntegration::None => {}
    }
    Ok(())
}

/// Create a temporary working directory for downloaded binaries under the
/// system temp root.
///
/// Returns the path of the newly created directory. The directory is not
/// cleaned up automatically -- it will be cleared on the next OS reboot or
/// when the installer runs again.
fn make_tempdir() -> Result<PathBuf, InstallError> {
    let base = std::env::temp_dir().join("kleos-install");
    std::fs::create_dir_all(&base)?;
    Ok(base)
}

/// Set the executable bit on a file (Unix-only).
///
/// Adds the execute permission for user, group, and other without removing
/// any existing read/write permissions.
#[cfg(unix)]
fn set_executable(path: &Path) -> Result<(), InstallError> {
    use std::os::unix::fs::PermissionsExt;
    let mut perms = std::fs::metadata(path)?.permissions();
    perms.set_mode(perms.mode() | 0o111);
    std::fs::set_permissions(path, perms)?;
    Ok(())
}
